# Generated by Django 3.0.5 on 2020-04-24 13:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conseil',
            name='nom',
        ),
        migrations.AddField(
            model_name='conseil',
            name='description',
            field=tinymce.models.HTMLField(default='test', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
